main: me.driftay.chatfilter.Main
name: ChatFilter
author: Driftay
version: ${project.version}
description: The Best Plugin For Managing Offensive Words
commands:
    chatfilter:
        description: Reload the Config.